
CREATE DATABASE IF NOT EXISTS covid;
USE covid;
 
/*DROP PROCEDURE IF EXISTS dummyRecords;*/
DROP TABLE IF EXISTS Encounters;
DROP TABLE IF EXISTS PhoneLocations;
DROP TABLE IF EXISTS Phone;

CREATE TABLE Phone (
  PhoneID INT NOT NULL PRIMARY KEY, PhoneNum VARCHAR(20)
);

/*
CREATE TABLE PhoneLocations (
  PhoneID INT NOT NULL, LocID INT NOT NULL, P0 POINT NOT NULL, SPATIAL INDEX ip0(P0), P1 POINT NOT NULL, SPATIAL INDEX ip1(P1), 
  T0 DATETIME, T1 DATETIME, T2 DATETIME, T3 DATETIME, Hard DOUBLE, Soft DOUBLE, 
  PRIMARY KEY (PhoneID, LocID), FOREIGN KEY (PhoneID) REFERENCES Phone(PhoneID)
);     */

CREATE TABLE PhoneLocations (
  PhoneID INT NOT NULL, LocID INT NOT NULL, Box POLYGON SRID 0 NOT NULL,
  T0 DATETIME, T1 DATETIME, T2 DATETIME, T3 DATETIME, Hard DOUBLE, Soft DOUBLE,
  PRIMARY KEY (PhoneID, LocID), SPATIAL INDEX ibox(Box), FOREIGN KEY (PhoneID) REFERENCES Phone(PhoneID)
); /* add index on T0?


CREATE TABLE Encounters (
  PhoneIDA INT, LocIDA INT, PhoneIDB INT, LocIDB INT, SpatialScore DOUBLE, TemporalScore DOUBLE,
  FOREIGN KEY (PhoneIDA, LocIDA) REFERENCES PhoneLocations(PhoneID, LocID)
);


